### ISSUE TITLE
Oh My Repos un işlevi nedir ?

### ISSUE THREAD

**Issue by ozkansen** [utkuufuk/ubuntu-on-steroids#7]
Merhaba,

Oh My Repos un işlevini anlayamadım tam olarak nedir ?

Teşekkürler.

**Comment by utkuufuk** [comment]
Merhaba,

Aşağıdaki bağlantılardan detaylı bilgiye ulaşabilirsin. Oh My Repos readme'sini zaten okuduysan bir de myrepos'a bak.

Oh My Repos: https://github.com/utkuufuk/oh-my-repos
myrepos: https://myrepos.branchable.com/

Özetle Oh My Repos, myrepos aracını kullanarak tek komutla bir dizinde bulunan tüm git repolarını pull'lamaya yarıyor.
